name: office_archiving
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_pdfview: ^1.3.2
  image_picker: ^1.1.2
  open_file: ^3.5.7
  path: ^1.8.0
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  shared_preferences: ^2.3.2
  sqflite: ^2.0.0+4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.14.3

  flutter_test:
    sdk: flutter
  rename: ^3.0.2
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_office.png"
  adaptive_icon_foreground: "assets/images/logo_office.png"
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
