name: office_archiving
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_pdfview: ^1.3.2
  image_picker: ^1.1.2
  animations: ^2.0.11
  open_file: ^3.5.7
  path: ^1.8.0
  path_provider: ^2.0.15
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  sqflite: ^2.0.0+4
  shimmer: ^3.0.0
  
  # AI Features Dependencies (temporarily disabled due to network issues)
  google_mlkit_text_recognition: ^0.12.0
  flutter_tesseract_ocr: ^0.4.21
  # google_mlkit_language_id: ^0.10.0
  http: ^1.1.0
  translator: ^1.0.0

  # PDF and Editor enhancements
  pdf: ^3.10.8
  printing: ^5.13.4
  image_editor_plus: ^1.0.8
  signature: ^5.5.0
  share_plus: ^10.0.2
  fl_chart: ^0.68.0
  media_store_plus: ^0.1.3
  image: ^4.2.0
  url_launcher: ^6.3.0
  flutter_colorpicker: ^1.1.0
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.3
  flutter_native_image: ^0.0.6+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.14.3

  flutter_test:
    sdk: flutter
  rename: ^3.0.2
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo_office.png
  adaptive_icon_foreground: assets/images/logo_office.png
  adaptive_icon_background: "#FFFFFF"
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/tessdata/

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
